# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/anike/fpga-flight-sim/flight_sim/flight_sim.srcs/sources_1/ip/faces_rom/faces_rom.xci
# IP: The module: 'faces_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anike/fpga-flight-sim/flight_sim/flight_sim.gen/sources_1/ip/faces_rom/faces_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'faces_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/anike/fpga-flight-sim/flight_sim/flight_sim.srcs/sources_1/ip/faces_rom/faces_rom.xci
# IP: The module: 'faces_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anike/fpga-flight-sim/flight_sim/flight_sim.gen/sources_1/ip/faces_rom/faces_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'faces_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
