# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/krishnan/Documents/fpga-flight-sim/flight_sim/flight_sim.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/krishnan/Documents/fpga-flight-sim/flight_sim/flight_sim.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/krishnan/Documents/fpga-flight-sim/flight_sim/flight_sim.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/krishnan/Documents/fpga-flight-sim/flight_sim/flight_sim.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
